DROP TABLE IF EXISTS CUSTOMER_INFO;
CREATE TABLE CUSTOMER_INFO AS (
  SELECT DISTINCT
    SSN,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    STREET,
    CITY,
    STATE,
    ZIP,
    LAT,
    LON,
    CITY_POP,
    JOB,
    DOB
  FROM TRANS_FACT);


DROP TABLE IF EXISTS TRANSACTION_HISTORY;
CREATE TABLE TRANSACTION_HISTORY AS (
  SELECT
    SSN,
    TRANSNUM,
    TRANSDATE,
    CATEGORY,
    AMT
  FROM TRANS_FACT);


DROP TABLE IF EXISTS ACCOUNT_INFO;
CREATE TABLE ACCOUNT_INFO AS (
  SELECT DISTINCT
    SSN,
    ACCT_NUM
  FROM TRANS_FACT);
