DROP TABLE IF EXISTS SPENDING_WITH_CUSTOMER_INFO;
CREATE TABLE SPENDING_WITH_CUSTOMER_INFO AS (
  SELECT
    C.*,
    S.NUM_TRANS,
    S.YEAR_MON,
    S.FOOD_DINING,
    S.UTILITIES,
    S.GROCERY_NET,
    S.HOME,
    S.PHARMACY,
    S.SHOPPING_POS,
    S.KIDS_PETS,
    S.PERSONAL_CARE,
    S.MISC_POS,
    S.GAS_TRANSPORT,
    S.MISC_NET,
    S.HEALTH_FITNESS,
    S.SHOPPING_NET,
    S.TRAVEL
  FROM CUSTOMER_INFO C
    JOIN SPENDING S ON C.SSN = S.SSN
);
