DROP TABLE IF EXISTS TRANS_FACT;
CREATE TABLE TRANS_FACT (
  SSN        VARCHAR(12),
  FIRST_NAME VARCHAR(10),
  LAST_NAME  VARCHAR(10),
  GENDER     VARCHAR(1),
  STREET     VARCHAR(30),
  CITY       VARCHAR(15),
  STATE      VARCHAR(2),
  ZIP        VARCHAR(5),
  LAT        DECIMAL,
  LON        DECIMAL,
  CITY_POP   INTEGER,
  JOB        TEXT,
  DOB        DATE,
  ACCT_NUM   BIGINT,
  PROFILE    TEXT,
  TRANSNUM   INTEGER,
  TRANSDATE  DATE,
  CATEGORY   TEXT,
  AMT        DECIMAL
);
